### ISSUE TITLE
Preview sequence diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#10]
![create_user2](https://user-images.githubusercontent.com/29195110/28398622-4bca7532-6d32-11e7-8916-25ea746badc0.jpg)
![listuser](https://user-images.githubusercontent.com/29195110/28398623-4bcab1c8-6d32-11e7-888c-212469437fd2.jpg)

Tụi em vẽ trước 2 sequence diagram, mấy anh review giúp tụi em trước để tụi em dựa theo làm tiếp ạ

**Comment by ghost** [comment]
LGTM. Thanks.
