### ISSUE TITLE
User - View Profile Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#12]

**Comment by karify98** [comment]
![use-view-profile.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46fd879f6e948aac98a4af51ab5bf9982c046b313916ac217586f76ae5002e58590b49ad440d5c46aaf9db23a6b638728b0e5ae4d46e4d68d47f40f2ecdd42e64bef62994597b5bd804dc5e83d20e488864b3c1606119bb2.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
