### ISSUE TITLE
User - Update Profile Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#13]

**Comment by karify98** [comment]
![user-update-profile.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46fd879f31cf96b98be8ab46e94de29b2f4f2b766b48e13b628ae92dbc56395b4d5a47aa155f5e41a9fa8b7da6e434708a5809ec833c5671c52f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e78b8a4c3d170d1e80fc5c27ed.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
