### ISSUE TITLE
User - Logout Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#14]

**Comment by AT-DuocNguyen** [comment]
![logout.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed67411f7b9001f9d94ff/125516c66e82c728ace21e0d46e49b9d2c9797ebc3abaf51ab57f5973d047d317c5df52f27d4b62dec107d510d574eac455a5e16adf08c28b4aa2e32db025fb28c341521842f1bbebb8315be04ba208e4c86b6be8b45c7eb2f68.jpg)

**Comment by duocnguyenc** [comment]
![logout.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed67411f7b9001f9d94ff/125516c66e82c728ace21e0d46e49b9d2c9797ebc3abaf51ab57f5973d047d317c5df52f27d4b62dec107d510d574eac455a5e16adf08c28b4aa2e32db025fb28c341521842f1bbeba8415be04ba208e4c82b4b58944c6ea2f68.jpg)

**Comment by ghost** [comment]
@AT-DuocNguyen 
`deleteSession()` hoặc là `logout()` thôi là được rồi.

**Comment by ghost** [comment]
LGTM. Thanks.
