### ISSUE TITLE
User - Rating and Comment Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#15]

**Comment by karify98** [comment]
![update.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46fd849e229686ebc3abaf51ab57f5973d047d317c5df52f27d4b62dec107d510d574eac455a5e16adf08c28b4aa2e32db025fb28c341521842f1bbebb8315be04ba218b4c83bfbd8f4ac0e92f68.jpg)

**Comment by ghost** [comment]
@at-namnguyen 
Phần GUI của rating page á, cái đó ko có.
Phần rating này dạng giống như comment của khách sạn á!
Nó ở phía dưới danh sách phòng.

**Comment by karify98** [comment]
ok a vậy sẽ rating ngay bên dưới Detail của hotel, em updae rồi a rv lại giúp em

**Comment by ghost** [comment]
@at-namnguyen Thanks. sau bước 2 cần có chỗ show validation error message chứ nhỉ?

**Comment by karify98** [comment]
ok, @at-nhuibo review lai giúp em, thanks  anh!

**Comment by ghost** [comment]
@at-namnguyen Chữ error viết sai tề! :D

**Comment by ghost** [comment]
LGTM. Thanks.
