### ISSUE TITLE
User - Search Hotel Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#16]

**Comment by duocnguyenc** [comment]
![SearchHotel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed67411f7b9001f9d94ff/125516c66e82c728ace21e0d46db919b31818b8180fdba4fe611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b921814e80b6bc8f4fc8e13a23e4838b5d73.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
