### ISSUE TITLE
User - See Detail Hotel Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#17]
![hotel_detail](https://user-images.githubusercontent.com/29195110/28568408-d9cf1898-715f-11e7-897a-763924bfcf73.jpg)

**Comment by AT-DuocNguyen** [comment]
![seedetailhotel](https://user-images.githubusercontent.com/29423614/28406420-c01ef43a-6d5a-11e7-9e1d-294a21a5db59.jpg)

**Comment by at-trungtranqn** [comment]
![detail_hotel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46ec918e228b8f9687e6ab46a81fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8a49c3ef352cee8a894b2c53.jpg)

**Comment by ghost** [comment]
@at-trungtranqn
Cái này là **User - See Detail Hotel Sequence Diagram** (title issue)
hay là **Admin - Delete hotel** (ảnh) vậy?

**Comment by at-trungtranqn** [comment]
ah mình up nhầm ảnh đó A Nhứi, mình fix rồi nha. thank :)

**Comment by ghost** [comment]
LGTM. Thanks.
