### ISSUE TITLE
User - Book Room Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#18]

**Comment by duocnguyenc** [comment]
![booking](https://user-images.githubusercontent.com/29423614/28566047-353acab8-7158-11e7-8ee8-a43b6569d5d7.jpg)

**Comment by ghost** [comment]
@AT-DuocNguyen 
bước 8, vs 9 có vẻ ngược ngược sao á nha?

**Comment by ghost** [comment]
LGTM. Thanks.
