### ISSUE TITLE
Guest - Register Accout Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#19]

**Comment by at-trungtranqn** [comment]
![register .jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fa919d2a9197ac9da9fd0fe64de29b234324676b5ee17e29d3e77fee177e525d094efe49585f40fef8db7aafb33f62964e49bc8f3900299f7744eeaa880dbd07b0218e4f85b3bf8d4cc5e13b21e399c2.jpg)

**Comment by ghost** [comment]
LGTM.
