### ISSUE TITLE
Guest - View Static Pages Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#20]

**Comment by at-trungtranqn** [comment]
![view_static_page.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fe9d9f34bd90bd8efdb6409b4df1932c046b313916ac217586f76ae5002e58590b49ad440d5c46aaf9db23a6b638728b0e5ae4d46e4d68d47f40f2ecdd42e64bef62994597b5bd804dc5e83d20e48c8e4f3b1b04109bb2.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
