### ISSUE TITLE
Guest - View Detail News Pages Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#23]

**Comment by karify98** [comment]
![guest-view-detail-news.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46ef819f3096cebf86eca80ea058e495204a6a7d2c13b0693cc7f33ab0487e021b4d44be44515910fbf88c7ea5b46a70d8540bedd56f5e26973414afaa9e0dfd50e474d412dcfce9c85ecafa3e24ed8a8a4f3e1b061c8cf65b3da6915985.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
