### ISSUE TITLE
Admin - Manager User -Update User Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#25]

**Comment by at-yenho** [comment]
![update user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99afaba51e611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b921814e80b6bc8f4fc6e13c20ee888f5d73.jpg)

**Comment by at-yenho** [comment]
![update user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99afaba51e611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b921814e80b6bc8f4fc8e03e26e68c8f5d73.jpg)

**Comment by HT-yen** [comment]
![update user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99afaba51e611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b921814e80b6bc8f4fc8e03524ef83875d73.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
