### ISSUE TITLE
Admin - Manager User - Search User Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#27]

**Comment by HT-yen** [comment]
![search user.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fb919b31818be99afaba51e611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b826814e80b6bc8f4fc6e13b20e4838b5d73.jpg)
