### ISSUE TITLE
Admin - Manager Hotel - Add Hotel Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#29]

**Comment by at-trungtranqn** [comment]
![add_hotel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46e9909e1c8a8cbd8ae5fd0fe64de29b234324676b5ee17e29d3e77fee177e525d094efe49585f40fef8db7aafb33f62964e49bc8f3900299f7744eeaa880dbc00b0218e4f85b3bf8d4ac1eb3923e399c2.jpg)

**Comment by karify98** [comment]
![addhotel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46e9909e2b8d97ac83abf301b44fff9e2c4533317346f6722681b479ea472853095f1ca441585b46fdabd822a3b52e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4f8db0b98a48c6ed3d24f5c6.jpg)

**Comment by ghost** [comment]
8,9 cũng không phải là confirm

**Comment by karify98** [comment]
Em sửa rồi a, a review lại giúp em với!
