### ISSUE TITLE
Admin - Manager Hotel -Update Hotel Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#30]

**Comment by at-trungtranqn** [comment]
![update_hotel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fd849e2296869687e6ab46a81fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8238a4584b3bc8a49c3ef382ce3828c4d2c53.jpg)

**Comment by at-namnguyen** [comment]
![update.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46fd849e229686ebc3abaf51ab57f5973d047d317c5df52f27d4b62dec107d510d574eac455a5e16adf08c28b4aa2e32db025fb28c341521842f1bbebb8315be04ba208e4c8db2bc834ec2ea2f68.jpg)

**Comment by karify98** [comment]
![update .jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46fd849e229686e9cda5fd53b652fa912a5265296b51fa7d74d2b27dba1129075f0d46ac415c5d45aea8802ea5a42062c80d55b98e30063e937f03a6aa811eb500bf208a4a82b2b5894bc3ea3d37aa.jpg)

**Comment by ghost** [comment]
- update phải check là có record ko mới làm tiếp
- 9, 10 không phải là confỉm, mà hiển thị thông báo ra thôi

**Comment by karify98** [comment]
em mới update lại, còn phần check record thì khi update trường id_hotel chỉ readOnly mà a, không cho sửa,

**Comment by ghost** [comment]
Ý a là trường hợp getHotelById đó

**Comment by karify98** [comment]
@at-thinhnguyen ok a, e mới update a review lại giúp em
