### ISSUE TITLE
Admin - Manager Hotel - Delete Hotel Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#31]

**Comment by at-trungtranqn** [comment]
![delete_hotel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46ec91962696869687e6ab46a81fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8a49c3ef3427ef8b8b462c53.jpg)

**Comment by karify98** [comment]
![addhotel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46e9909e2b8d97ac83abf301b44fff9e2c4533317346f6722681b479ea472853095f1ca441585b46fdabd822a3b52e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4f8db0b98f48c6ef3521f5c6.jpg)

**Comment by ghost** [comment]
6,7 ko phải confirm, mà chỉ show message ra thôi

**Comment by karify98** [comment]
em mới update lại rồi, a review lại giúp em ạ!
