### ISSUE TITLE
Admin - Manager Hotel - Search Hotel Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#32]

**Comment by at-namnguyen** [comment]
![Image_from_Skype2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46c1999b2487bcaf9de6b27c9756e9842c14653f6b14b1247a80e03cfd18395456591aab405d0a47feaf8979aeb63c74885d59bcd8685c66da2f53fde6d640e258f075c95d8fa4bf8b46c1ed3d25e28888483f16041b88ed10.jpg)

**Comment by at-namnguyen** [comment]
![search.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46fb919b31818bebc3abaf51ab57f5973d047d317c5df52f27d4b62dec107d510d574eac455a5e16adf08c28b4aa2e32db025fb28c341521842f1bbebb8315be04ba208e4c8cb3bb894ac2ea2f68.jpg)

**Comment by duocnguyenc** [comment]
![manSearchHotel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed67411f7b9001f9d94ff/125516c66e82c728ace21e0d46e59594108782bb8ce1974cb058fcd665043761260ea62864c7b96aea1b2d05585e4bf9425a0944aef1892ba2b43d22db550eeec3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0ed3e2cef8b8a4e3f181755.jpg)
