### ISSUE TITLE
Admin - Manager Hotel - View List Of Hotel Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#33]

**Comment by karify98** [comment]
![Image_from_Skype.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46c1999b2487bcaf9de6b27c9756e9842c046b313916ac217586f76ae5002e58590b49ad440d5c46aaf9db23a6b638728b0e5ae4d46e4d68d47f40f2ecdd42e64bef62994597b5bd804dc5e83d20e48c894b3f1802189bb2.jpg)
