### ISSUE TITLE
Admin - Manager Service - Create Service Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#34]

**Comment by HT-yen** [comment]
![create services.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46eb869f229686e99cecad55ad5ef5876b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d87b0b68b49c0e83a21e48d8b4d3719010ac4.jpg)
fix ' create service', please check my comment

**Comment by ghost** [comment]
Bước 8, 9 đâu phải là confirm đâu, chỉ cần hiển thị thông báo ok hoặc error thôi

**Comment by at-yenho** [comment]
![create services.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46eb869f229686e99cecad55ad5ef5876b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d87b0b68b49c0e83a21e48b8848381d020ac4.jpg)

fix ' create service', please check my comment

**Comment by ghost** [comment]
LGTM
