### ISSUE TITLE
Admin - Manager Service - Update Service Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#35]

**Comment by at-yenho** [comment]
![update service.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99cecad55ad5ef5d665043761260ea62864c7b96aea1b2d05585e4bf9425a0944aef1892ba2b43d22db550eeec3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc0ed3e22e78d88493b1e1755.jpg)

**Comment by HT-yen** [comment]
![update service.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99cecad55ad5ef5d665043761260ea62864c7b96aea1b2d05585e4bf9425a0944aef1892ba2b43d22db550eeec3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0ef3927e0828d4c3a1e1755.jpg)
fix ' update service', please check my comment

**Comment by ghost** [comment]
- Update phải check là có record ko mới làm tiếp, nên chia bước 3 thành 2 bước: có hoặc ko có record

**Comment by ghost** [comment]
LGTM
