### ISSUE TITLE
Admin - Manager Service - Delete Service Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#36]

**Comment by HT-yen** [comment]
![detele service.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46ec918e268e86e99cecad55ad5ef5d665043761260ea62864c7b96aea1b2d05585e4bf9425a0944aef1892ba2b43d22db550eeec3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0ef3926e2828f473c161755.jpg)

**Comment by at-yenho** [comment]
![detele service.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46ec918e268e86e99cecad55ad5ef5d665043761260ea62864c7b96aea1b2d05585e4bf9425a0944aef1892ba2b43d22db550eeec3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0ef3926e7898f4a3d1f1755.jpg)

**Comment by ghost** [comment]
LGTM
