### ISSUE TITLE
Admin - Manager Service - Search Service Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#37]

**Comment by HT-yen** [comment]
![search service.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fb919b31818be99cecad55ad5ef5d665043761260ea62864c7b96aea1b2d05585e4bf9425a0944aef1892ba2b43d22db550eeec3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0ed3e22e68a864c39161755.jpg)

**Comment by ghost** [comment]
LGTM
