### ISSUE TITLE
Admin - Manager Service - View List Of Service Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#38]

**Comment by HT-yen** [comment]
![list  services.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46e49d8937c2c3ba8afba94aa758e3d665043761260ea62864c7b96aea1b2d05585e4bf9425a0944aef1892ba2b43d22db550eeec3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc1ec3526e18d8b4a37161755.jpg)

em fix rồi .. mấy anh check giùm em với

**Comment by ghost** [comment]
service nằm trong room luôn à ?

**Comment by ghost** [comment]
@at-thinhnguyen @at-yenho Service nằm trong hotel nha! Ko phải trong room.
Trong phần detal của edit/new hotel có mục chọn service. Cái này mình chỉ đi tick mà thôi.
Click vào button thêm service thì sẽ chuyển sang trang thêm service, xong thì trở lại trang edit/new hotel.

**Comment by ghost** [comment]
LGTM
