### ISSUE TITLE
Use-case diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#4]
![usecase_general](https://user-images.githubusercontent.com/29195110/28378515-a42832da-6cda-11e7-9ae8-cf69160961be.jpg)

 
![admin_usecase_general](https://user-images.githubusercontent.com/29195110/28378470-76731846-6cda-11e7-8546-d7f9ca584cc5.jpg)

![manage_user](https://user-images.githubusercontent.com/29195110/28375662-3de74068-6cd2-11e7-903e-ccf3888c8932.jpg)
![manage_hotel](https://user-images.githubusercontent.com/29195110/28375670-444930e2-6cd2-11e7-81ff-cfe86bce2faf.jpg)
 
![manage_room](https://user-images.githubusercontent.com/29195110/28377625-97fcbca4-6cd7-11e7-8733-8968898ec0d1.jpg)

![manage_service](https://user-images.githubusercontent.com/29195110/28377605-8ceab06e-6cd7-11e7-9d66-778ab74ff7c1.jpg)

![manage_feedback](https://user-images.githubusercontent.com/29195110/28375679-4b190b68-6cd2-11e7-95e8-10b1d30de518.jpg)
 
![manage_bookingroom](https://user-images.githubusercontent.com/29195110/28375831-c6b22246-6cd2-11e7-919d-f755a3fb09ca.jpg)

 
![manage_staticpage](https://user-images.githubusercontent.com/29195110/28375921-06ee57bc-6cd3-11e7-94a5-98ee57397eaf.jpg)

 
 
![manage_place](https://user-images.githubusercontent.com/29195110/28396318-bdbf16ba-6d24-11e7-902e-e5a276453144.jpg)

![manage_comment](https://user-images.githubusercontent.com/29195110/28375721-6a6b3856-6cd2-11e7-8626-326df98f212b.jpg)
 
![manage_news](https://user-images.githubusercontent.com/29195110/28376089-674d0374-6cd3-11e7-91b9-135ddd33b32e.jpg)

![manage_new_category](https://user-images.githubusercontent.com/29195110/28375751-7ece93e2-6cd2-11e7-82b5-a92740487cc7.jpg)

 
 

# Break down
|    Actor     |    Use-case     |      Action      |
| :----------: | :-------------: | :--------------: |
| | Guest | Register | Create|
| Guest, User | Search hotel|   Read |
| Guest, User | View list of hotel| Read |
| Guest, User | View detail hotel|  Read |
| Guest, User | View list of News|  Read |
| Guest, User | View detail News|   Read |
| Guest, User | View static pages|  Read |
| Guest, User |Feedback|    Create |
| User | Comment & Rating | Create |
| User | View list of comment  | Read |
| User | Comment & Rating | Update |
| User | Comment & Rating | Delete |
| User | View History Booking | Read |
| User | View History Booking | Delete |
| User | View History Booking | Update |
| User | View profile | Read|
| User | Update profile |   Update |
| User | Booking room | Create | 
| Admin |   Manage users | Create |
| Admin |   Manage users   | Read |
| Admin |   Manage users | Update |
| Admin |   Manage users    | Delete |
| Admin |   Manage Hotels | Read |
| Admin |   Manage Hotels | Create |
| Admin |   Manage Hotels | Delete |
| Admin |   Manage Hotels | Update |
| Admin |   Manage rooms   | Read|
| Admin |   Manage rooms    | Create|
| Admin |   Manage rooms    | Update|
| Admin |   Manage rooms    | Delete|
| Admin |   Manage Services |  Read|
| Admin |   Manage Services |   Create|
| Admin |   Manage Services |   Delete|
| Admin |   Manage Services |   Update|
| Admin |   Manage comments | Read |
| Admin |   Manage comments | Delete|
| Admin |   Manage booking rooms | Read |
| Admin |   Manage booking rooms | Update |
| Admin |   Manage booking rooms | Delete |
| Admin |   Manage Feedback|    Read |
| Admin |   Manage Feedback|    Delete |
| Admin | Manage Static Pages | Update |
| Admin | Manage news category  | Read |
| Admin | Manage news category  | Create |
| Admin | Manage news category  | Update |
| Admin | Manage news category  | Delete |
| Admin | Manage  news | Read |
| Admin | Manage  news | Create |
| Admin | Manage  news | Update |
| Admin | Manage  news | Delete |
| Admin | Manage place | Read |
| Admin | Manage place | Update |
| Admin | Manage place | Delete |
| Admin | Manage place | Create |

# Đặc tả Use-case
### 1.1 Guest: 
Là người chưa có tài khoản trong hệ thống, chỉ được phép dùng các chức năng ở trang home của hệ thống.Không thể giao dịch với hệ thống. Và có quyền đăng kí tài khoản để được quyền sử dụng các chức năng khác của hệ thống.

### 1.2 User: 
Là người đã có tài khoản của hệ thống, có quyền thực hiện các chức năng book phòng, xem, sửa thông tin cá nhân,... khi đăng nhập thành công vào hệ thống.

### 1.3 Admin: 
Là người có quyền cao nhất trong hệ thống, là người quản lý các thành viên, quản lý các khách sạn trong hệ thống, quản lý việc đặt phòng

### 2.1.1 Register

<table>
    <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Chưa đăng nhập vào hệ thống</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Khi user chọn hủy bỏ việc đăng nhập hoặc tắt trình duyệt, use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Khách viếng thăm có thể đăng kí tài khoản để sử dụng chức năng hệ thống</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhập tên tài khoản, email, mật khẩu và một số thông tin khác</td>
        <td>- Lấy thông tin và kiểm tra có hợp lệ không <br/>- Nếu thành công tài khoản sẽ được khởi tạo, ngược lại thông báo không thành công.
        </td>
    </tr>
</table>

### 2.1.2 Search

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest/ User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Truy cập vào website</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng không nhấn nút tìm kiếm mà chuyển trang hoặc tắt trình duyệt , use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng tìm kiếm khách sạn theo khu vực vị trí, ngày nhận phòng, ngày trả phòng  </td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhập vị trí khách sạn, ngày nhận phòng, ngày trả rồi nhấn nút tìm kiếm</td>
        <td>- Lấy thông tin và kiểm tra trong cơ sở dữ liệu xem có khách sạn nào vừa thõa mãn vị trí nhập vào vữa có phòng trống trong khoảng thời gian từ ngày nhận đến ngày trả <br/>- Nếu có trả về danh sách khách sạn thõa mãn, ngược lại thông báo không tìm thấy.
        </td>
    </tr>
</table>

### 2.1.3 View hotel  detail 

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest/ User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Truy cập vào website</td>
    </tr>
     <tr>
        <td>Điều kiện sau </td>
        <td colspan="2">Người dùng  tắt trình duyệt, use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng xem thông tin chi tiết về khách sạn mình cần</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Click vào hình ảnh hoặc tên khách sạn </td>
        <td>- Lấy thông tin, tiến hành tìm kiếm trong cơ sở dữ liệu.<br>
		- Hệ thống chuyển đến trang chi tiết của khách sạn cần xem.
        </td>
    </tr>
</table>

### 2.1.4 View news

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest/ User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Truy cập vào website</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng tắt trình duyệt, use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng xem một số tin tức về  các sự kiện, khuyến mãi, ưu đãi, thông tin công ty</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Click vào hình ảnh hoặc tiêu đề tin tức được public cho mọi người khi truy cập vào website </td>
        <td>- Lấy thông tin, tiến hành tìm kiếm trong cơ sở dữ liệu.<br>
		- Hệ thống chuyển đến trang chi tiết của tin tức cần xem.
        </td>
    </tr>
</table>
 
### 2.1.5 Feedback

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">Guest/ User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Truy cập vào website</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng nhấn nút Hủy bỏ hoặc tắt trình duyệt, use case sẽ kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng phản hồi, đóng ý kiến chung về website, dịch vụ,.. cho admin</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Click form feedback, nhập tài khoản email, ý kiến phản hồi,... rồi nhấn nút send </td>
        <td>- Lấy thông tin gửi về, tiến hành lưu vào cơ sở dữ liệu.<br>
		- Khi lưu thành công, hệ thống gửi thông báo cho người dùng về việc gửi feedback thành công
        </td>
    </tr>
</table>

### 2.1.6 View profile 

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào website và truy cập vào trang cá nhân</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng  đăng xuất hoặc tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng thay đổi thông tin cá nhân đăng ký trên website (full name, pasword, address, birthday  )</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào phần xem thông tin cá nhân</td>
        <td>-  Hiển thị trang thông tin cá nhân gồm nội dung được nhập  lúc user đăng ký 
        </td>
    </tr>
</table>

### 2.1.7 Update profile 

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào website</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng  hủy bỏ thao tác cập nhật thông tin profile hoặc chuyển trang trước khi lưu thông tin, đăng xuất hoặc tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng thay đổi thông tin cá nhân đăng ký trên website (full name, pasword, address, birthday, avatar  )</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào phần chỉnh sửa thông tin cá nhân<br>- Nhấn lưu thay đổi  </td>
        <td>-  Hiển thị trang chỉnh sửa thông tin cá nhân gồm nội dung  trên các ô text box cho phép chỉnh sửa thông tin <br>- Cập nhật nội dung  trên các ô nhập liệu vào cơ sở dữ liệu nếu dữ liệu nhập vào hợp lệ
        <br> - Hiển thị thông báo thay đổi thông tin cá nhân thành công cho người dùng
        </td>
    </tr>
</table>

### 2.1.8 Logout

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> User/Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào website</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2">Người dùng không nhấn nút logout</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Người dùng phản hồi, đóng ý kiến chung về website, dịch vụ,.. cho admin</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>-Nhấn vào  đăng xuất  </td>
        <td>-  Xóa session và reload lại trang, hoặc chuyển về home page nếu user đang ở những trang yêu cầu đăng nhập mới được phép truy cập<br>
        </td>
    </tr>
</table>

### 2.2.1 Comments

<table>
    <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào hệ thống</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc</td>
        <td colspan="2">User không submit nội dung comment mà chuyển trang hoặc tắt trinh duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Cho phép người dùng bình luận về các tin tức, và bài viết</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
   <tr>
        <td valign="top">- Nhập bình luận và bấm gửi</td>
        <td valign="top">- Hiển thị 1 form cho phép người dùng nhập bình luận <br>- Nếu hợp lệ thì lưu trữ vào CSDL và hiển thị ở phần bình luận của bài viết <br>
        </td>
    </tr>
</table>

## 2.2.2 View histories book

<table>
    <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào hệ thống</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc</td>
        <td colspan="2">Khi người dùng click button 'Quay về' hoặc chuyển trang, tắt trình duyệt thì use-case kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Cho phép người dùng xem lại lịch sử đặt phòng của mình</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
   <tr>
        <td valign="top">- Click button View histories book</td>
        <td valign="top">- Hiển thị table lịch sử đặt phòng, dữ liệu được lấy từ database
        </td>
    </tr>
</table>
## 2.2.3 Rating

<table>
    <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2">User</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào hệ thống</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc</td>
        <td colspan="2">Khi người dùng click button 'Hủy' hoặc chuyển trang, tắt trình duyệt use-case kết thúc</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Cho phép người dùng đánh giá chi tiết về các khách sạn</td>
    </tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
   <tr>
        <td valign="top">- Click button 'Đánn giá'<br>- Điền nội dung vào form đánh giá và submit<br> </td>
        <td valign="top">- Hiển thị form đánh giá cho người dùng, bao gồm 5 tiêu chí mỗi tiêu tối đa 10 điểm<br> - Lưu trữ vào database
        </td>
    </tr>
</table>

### 2.3.1 Manage user

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào trang admin</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"> Admin đăng xuất hoặc chuyển trang, tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Admin xem danh sách tất cả các user đã đăng ký làm thành viên của website</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào phần Quản lý Người dùng <br>- Nhấn Thêm/Sửa/Xóa các user </td>
        <td  style='vertical-align : top; '>-  Hiển thị trang liệt kê tất cả các user đã đăng ký, sắp xếp theo user mới nhất giảm dần <br>
         - Truy vấn cơ sở dữ liệu và thực hiện các hành động tương ứng Thêm/Cập nhật/Xóa  <b>user</b> 
        </td>
    </tr>
</table>
###  2.3.2 Manage comment 

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào trang admin</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"> Admin đăng xuất hoặc chuyển trang, tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Admin xem danh sách tất cả bình luận mà user đã viết cho các khách sạn, cho phép hoặc không cho phép bình luận hiển thị lên website. Xóa bình luận</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào phần Quản lý bình luận<br>- Nhấn duyệt hoặc Bỏ duyệt <br> -  Đánh dấu chọn bình luận và nhấn xóa </td>
        <td  style='vertical-align : top; '>-  Hiển thị trang liệt kê tất cả bình luận của user cho các khách sạn, sắp xếp theo comment mới nhất giảm dần 
        <br> - Cập nhật trạng thái của bình luận sang <b>hiển thị</b> (nếu ở trạng thái đang chờ hoặc không hiển thị) hoặc <b>không hiển thị </b>(nếu ở trạng thái đang chờ hoặc hiển thị)<br>-Truy vấn cơ sở dữ liệu để tìm những bình luận tương ứng và tiến hành xóa các bình luận <br>- Hiển thị thông báo xóa thành công cho admin 
        </td>
    </tr>
</table>
### 2.3.3 Manage hotel 

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào trang admin</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"> Admin đăng xuất hoặc chuyển trang, tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Admin xem danh sách tất cả khách sạn, và kèm theo đó là services, room, access book room</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào Quản lý khách sạn <br>- Nhấn Thêm Khách sạn/  <br> -  Sửa/Xóa Khách sạn 
         </td>
        <td  style='vertical-align : top; '>-  HIển thị danh sách tất cả các khách sạn
        <br> -  Thêm  khách sạn kèm theo các thông tin cần thiết cho khách sạn đó   vào cơ sở dữ liệu <br> - Truy vấn dữ liệu và thực hiện các hành động tương ứng với hotel tương ứng
        <br>- Hiển thị thông báo sửa/xóa thành công cho admin 
        </td>
    </tr>
</table>

### 2.3.4 Manage room

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào trang admin, và vào phần quản lý khách sạn, chọn khách sạn </td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"> Admin đăng xuất hoặc chuyển trang, tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Admin xem danh sách tất cả các phòng có trong khách sạn,  và các thông tin phòng kèm theo</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    <tr>
        <td style='vertical-align : top; '>- Nhấn vào thêm phòng  <br> -  Nhấn Sửa/Xóa phòng 
         </td>
        <td  style='vertical-align : top; '>-  HIển thị form cho phép nhập thông tin phòng mới
        <br> -  Thêm  phòng  kèm theo các thông tin cần thiết của phòng khách sạn  vào cơ sở dữ liệu <br> - Truy vấn dữ liệu và thực hiện các hành động sửa/xóa tương ứng với phòng tương ứng
        <br>- Hiển thị thông báo sửa/xóa thành công cho admin 
        </td>
    </tr>
</table>
### 2.3.5 Manage booking room

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào trang admin</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"> Admin đăng xuất hoặc chuyển trang, tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Admin xem danh sách tất cả đơn đặt phòng của user và guest</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào Quản lý đặt phòng <br>- Nhấn nút 'Duyệt đơn'    <br>  - Nhấn nút 'Xóa'    <br>  
         </td>
        <td  style='vertical-align : top; '>-  HIển thị danh sách tất cả các đơn đặt phòng
        <br> -  Thay đổi trạng thái đơn đặt phòng từ trạng thái đang chờ sang trạng thái đã chấp nhận <br> - Truy vấn dữ liệu và thực hiện xóa các hotel tương ứng
        <br>- Hiển thị thông báo sửa/xóa đơn đặt phòng thành công cho admin 
        </td>
    </tr>
</table>

### 2.3.6 Manage service

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào trang admin</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"> Admin đăng xuất hoặc chuyển trang, tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Admin xem danh sách tất cả các dịch vụ có trong hệ thống các khách sạn</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào Quản lý dịch vụ <br>- Nhấn Thêm dịch vụ     <br>- Nhấn Ok <br>  - Chọn dịch vụ và  nhấn nút sửa/xóa dịch vụ    <br>  
         </td>
        <td  style='vertical-align : top; '>-  HIển thị danh sách tất cả các dịch vụ hiện có 
        <br> - HIển thị form cho phép nhập các thông tin của một dịch vụ mới   <br> - Nếu dữ liệu nhập vào hợp lệ thì tiến hành lưu  dịch vụ vào cơ sở dữ liệu<br>- Truy vấn dữ liệu và thực hiện cập nhật/xóa các dịch vụ  tương ứng
        <br>- Hiển thị thông báo sửa/xóa dịch vụ thành công   
        </td>
    </tr>
</table>

### 2.3.7 Manage static pages 

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào trang admin</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"> Admin đăng xuất hoặc chuyển trang, tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Admin xem danh sách news/ introduce. Thêm/Sửa/Xóa news. Sửa/Xóa introduce</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào phần Quản lý tin tức/ AboutMyHotel<br>- Thêm/Sửa/Xóa news <br> -  Sửa/Xóa introduce </td>
        <td  style='vertical-align : top; '>-  Hiển thì trang tin tức/ giới thiệu
        <br> - Thực hiện các tác vụ cần thiết của news và introduce<br>-Truy vấn cơ sở dữ liệu  <br>- Hiển thị thông báo xóa thành công cho admin 
        </td>
    </tr>
</table>

### 2.3.8 Manage feedback 

<table>
   <tr>
        <th>Thuộc tính</th>
        <th colspan="2">Mô tả</th>
    </tr>
     <tr>
        <td>Tác nhân</td>
        <td colspan="2"> Admin</td>
    </tr>
     <tr>
        <td>Điều kiện trước </td>
        <td colspan="2">Đã đăng nhập vào trang admin</td>
    </tr>
     <tr>
        <td>Điều kiện kết thúc </td>
        <td colspan="2"> Admin đăng xuất hoặc chuyển trang, tắt trình duyệt</td>
    </tr>
        <tr>
        <td>Mô tả </td>
        <td colspan="2">Admin xem danh sách feedback của khách hàng. Response các feedback</tr>
    <tr>
        <td rowspan="2">Kịch bản</td>
         <th>Hành động của tác nhân</th>
        <th>Hành động của hệ thống</th>
    </tr>
    
   <tr>
        <td style='vertical-align : top; '>- Nhấn vào phần Feedback<br>- Replied feedback  </td>
        <td  style='vertical-align : top; '>-  Hiển thì trang feedback
        <br> - Thực hiện các tác vụ cần thiết của news và introduce<br>-Truy vấn cơ sở dữ liệu  <br>- Hiển thị thông báo xóa thành công cho admin 
        </td>
    </tr>
</table>

**Comment by ghost** [comment]
@at-trungtranqn trung
Thêm phần:
- News
- Comment - rating

Và mấy cái trong cuộc họp nữa nha!

**Comment by at-trungtranqn** [comment]
ok A Nhứi, mình thêm rồi nha, có bổ sung phần đặc tả use case, check giúp mình với nha

**Comment by ghost** [comment]
User:
- Vì sao rating và comment lại 1 use case nhỉ?
- Nên có use case cho: Xem danh sách news, chi tiết news
- Chỗ View histories booking sao lại có phần "UPDATE"? history chỉ xem hoặc delete thôi
- Chỗ break down task anh thấy không rõ ràng:
+ Ví dụ: User | View profile | Read, update. Nó hơi confuse vì đã là "view profile" thì sao lại "update". Nên a có suggest chỗ này. Use case em nên đặt đúng chức năng. Điều này sẽ thể hiện đầy đủ chức năng trên use-case và nó đồng bộ tên khi vẽ sequence. Trường hợp này anh suggest nên đặt use-case đầy đủ là: view profile, update profile

**Comment by at-trungtranqn** [comment]
- Phần rating và comment A Nhứi yêu cầu gộp vào anh
- Phần view history booking là xem lịch sử đặt phòng của user, cho phép user cập nhật lại  thông tin đơn đặt phòng nếu trạng thái đơn đặt phòng là đang chờ.
Còn phần news và breakdown tụi e sửa rồi đó anh.A check lại giúp tụi em với :)

**Comment by ghost** [comment]
@at-trungtranqn phần *admin* á:
- Một số mục khác: news, feedback, comments: ko có thêmm sửa, xoá và tìm kiếm hả?
- Phần khác thiếu:
  + Quản lý tỉnh, thành phố, quận, huyện
  + Quản lý categories của news

**Comment by ghost** [comment]
LGTM. Thanks.
