### ISSUE TITLE
Admin - Manager Room - Update Room Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#40]

**Comment by at-yenho** [comment]
![update room.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99de6b04ee611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b921814e80b6bc8f4fc7ea382de2838b5d73.jpg)

**Comment by HT-yen** [comment]
![update room.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99de6b04ee611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b921814e80b6bc8d48c3eb3a22e78f875d73.jpg)
