### ISSUE TITLE
Admin - Manager Room - Delete Room Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#41]

**Comment by HT-yen** [comment]
![detele room.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46ec918e268e86e99de6b04ee611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b921814e80b6bc8d48c3eb3f21e58b8f5d73.jpg)

**Comment by ghost** [comment]
Khi delete room thì phải check xem id room có tồn tại hay không nữa. 
với khi delete room thì phải check điều kiện ràng buộc của các bảng khác có liên quan đến room sẽ thế nào. VD xoá room thì có xoá các order liên quan đến room đó hay không?

**Comment by HT-yen** [comment]
![delete room.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46ec9196269686e99de6b04ee611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b921814e80b6bd8f44c8ea3825e48f895d73.jpg)

**Comment by ghost** [comment]
số 5. không tìm ra room thì phải báo lỗi chứ @at-yenho ?

**Comment by HT-yen** [comment]
Dạ, em fix lại rồi , a check lại giùm e với

**Comment by ghost** [comment]
LGTM
