### ISSUE TITLE
Admin - Manager Room - Search Room Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#42]

**Comment by HT-yen** [comment]
![search room.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fb919b31818be99de6b04ee611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b826814e80b6bc8f4fc7eb3c27e788875d73.jpg)

**Comment by ghost** [comment]
cai này có phần search nâng cao không?
