### ISSUE TITLE
Admin - Manager Feedback - Delete Feedback Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#45]

**Comment by at-trungtranqn** [comment]
![Delete_feedback.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46cc91962696869689ecba47a65cf39f6b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d86b7b68b49c0e83821e58a884b3a160d0ac4.jpg)

**Comment by ghost** [comment]
Mình nghĩ là <GUI> Feedback list, khi xoá nên có confirm

**Comment by annq3012** [comment]
Dạ. Delete đều có confirm xác nhận hết anh. Em không vẽ vào đó anh

**Comment by ghost** [comment]
phải vẽ vào chớ chế :D

**Comment by at-annguyen** [comment]
![feedback-delete.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46ee919f278082aa84a4bb46a858e4916b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d86b7b68b49c0e9382de488884c3f1f030ac4.jpeg)

**Comment by ghost** [comment]
nếu cancel thì nó đâu báo lỗi gì đâu

**Comment by annq3012** [comment]
![feedback-delete.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46ee919f278082aa84a4bb46a858e4916b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d87b0b68b49c0e9382de38d8c4e3a180d0ac4.jpeg)

**Comment by annq3012** [comment]
![feedback-delete.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46ee919f278082aa84a4bb46a858e4916b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d87b0b68b49c0e9382de38289473b16030ac4.jpeg)
