### ISSUE TITLE
Admin - Manager Booking Room - View List Of Booking Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#46]

**Comment by karify98** [comment]
![admin-viewlistofteam.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46e990972a8ccebf86eca84fad4ee49b2f5222722446ef696097ec22ba416f43554d4ba5470c5845f9ac8a29f0b66e788a5c0fefd03f0e7dc33e03b0aac04ee155e57dd205d0f4ae805ec3e93724e28b8f4a3d1807198ef75b34b2d4.jpg)
