### ISSUE TITLE
Admin - Manager Booking Room - Update Status Booking Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#47]

**Comment by karify98** [comment]
![admin-updatestatusbooking.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46e990972a8ccebc9fedbe57a14ee4953d533471260ba8227e82a164fd52690e050a1de853524d41f5ffdd2ca7b36973880a0bbfd96d5f70c43c43fdb1871cad1da862da11d1e9e1d30695aa2f2ff58989453f1b05188cfc5b3da9904dcb50e406.jpg)

**Comment by ghost** [comment]
Update status còn trường hợp fail nữa và approve, disapprove là status ko nên chia ra

**Comment by ghost** [comment]
Anh Minh review thêm nhá
