### ISSUE TITLE
Admin - Manage Booking Room - Delete Booking Room History Sequence

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#48]

**Comment by duocnguyenc** [comment]
![manDelBooking.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed67411f7b9001f9d94ff/125516c66e82c728ace21e0d46e5959407878f8b80e6b44aaa5ab2d86b56357c2301a03f32dfa17de6147f565e5a1baf430e5f16f4f9892fa4b76e21835908ffcd7f1d2598694ef1e1c84afd13b03289498fb7b98a4cc9ee3922e08c8f4a380c48.jpg)

**Comment by ghost** [comment]
khi xoá nên có confirm nhá

**Comment by duocnguyenc** [comment]
Em sửa lại rồi anh review lại giúp em.

**Comment by ghost** [comment]
còn thiếu case cancel khi confirm

**Comment by ghost** [comment]
LGTM
