### ISSUE TITLE
Admin - Manager Static Pages  - Update Static Page Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#49]

**Comment by at-yenho** [comment]
![update static pages.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99cfdbe57ad5eb084284122606b48e13b628ae92dbc56395b4d5a47aa155f5e41a9fa8b7da6e434708a5809ec833c5671c52f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e78b8a4c391d0d1981f65527ed.jpg)

**Comment by at-yenho** [comment]
![update static pages.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99cfdbe57ad5eb084284122606b48e13b628ae92dbc56395b4d5a47aa155f5e41a9fa8b7da6e434708a5809ec833c5671c52f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e78b8a4c3619061b8efc5827ed.jpg)

**Comment by HT-yen** [comment]
![update static pages.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99cfdbe57ad5eb084284122606b48e13b628ae92dbc56395b4d5a47aa155f5e41a9fa8b7da6e434708a5809ec833c5671c52f0dbefad341eb5ee779c11ac7a4b6984fc1e23c20e78b884b3d1f061080fb5f27ed.jpg)

**Comment by at-yenho** [comment]
![update static pages.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46fd849e229686e99cfdbe57ad5eb084284122606b48e13b628ae92dbc56395b4d5a47aa155f5e41a9fa8b7da6e434708a5809ec833c5671c52f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e78b884b3d1c05108bff5f27ed.jpg)
