### ISSUE TITLE
Admin - Manager Place - Update Place Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#52]

**Comment by at-trungtranqn** [comment]
![Update_place.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46dd849e229686969fe5be40a11fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8a49c3ee3b22e4898c472c53.jpg)

**Comment by at-trungtranqn** [comment]
![update_place2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fd849e229686969fe5be40a10fb2d86b56357c2301a03f32dfa17de6147f565e5a1baf430e5f16f4f9892fa4b76e21835908ffcd7f1d2598694ef1e1c84afd13b032884e8fb7b98a4cc5eb352de7888c4e370c48.jpg)

**Comment by ghost** [comment]
LGTM
