### ISSUE TITLE
Admin - Manager Place - Delete Place Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#53]

**Comment by at-trungtranqn** [comment]
![delete_place.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46ec9196269686969fe5be40a11fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8238a4584b3bc8a49c3ee3a21e58a89482c53.jpg)

**Comment by ghost** [comment]
LGTM

**Comment by ghost** [comment]
Cần kiểm tra place có tồn tại hay không nữa. 
Khi xoá place thì các bảng quan hệ với place sẽ thế nào?

**Comment by at-trungtranqn** [comment]
![delete_place.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46ec9196269686969fe5be40a11fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8238a4584b3bc8b49c7e83d2def828a4e2c53.png)
e update lại rồi nha anh .A check giúp em với, thank anh

**Comment by ghost** [comment]
LGTM
