### ISSUE TITLE
Admin - Manager Place - Search Place Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#54]

**Comment by at-trungtranqn** [comment]
![search_place.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fb919b31818b969fe5be40a11fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8a49c3ee3522e68e89492c53.jpg)

**Comment by ghost** [comment]
LGTM
