### ISSUE TITLE
Admin - Manager Comment - View List Of Comment Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#55]

**Comment by at-trungtranqn** [comment]
![List_comment.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46c49d8937bd80a682e4ba4db01fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8238a4584b3bc8a49c4ea3c20e38f8a462c53.jpg)

**Comment by ghost** [comment]
Thiếu phần getListCommentByHotelId()

**Comment by annq3012** [comment]
![cmt-view](https://user-images.githubusercontent.com/26828657/28771902-b2f924c6-760e-11e7-81b6-70de9ad590e9.jpeg)

**Comment by at-trungtranqn** [comment]
@at-minhnguyen  A Minh review giúp tụi em với ạ

**Comment by ghost** [comment]
ko cần throw Exception đâu, ko có thì null thôi

**Comment by at-trungtranqn** [comment]
![admin_view_comment.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46e990972a8cbcbf86eca87ca752fd992c4833316546b3397f8fe62bab0021435a5648f846595a11fffbdf2bf4be3c708e5e0abf80645a77d42103eee9dc4be05ce36ade0d97bcae894dcae93825e68c8d46361e00198df84f78.jpg)
A Thịnh check lại giúp e nha . Thank anh :)

**Comment by ghost** [comment]
@at-trungtranqn Ko cần số 6 đâu.

**Comment by ghost** [comment]
Send database chia thêm 1 cái nữa, là hiển thị thông báo "Không có comment nào" chứ ko cần trả về Index

**Comment by at-trungtranqn** [comment]
đã fix nha @at-nhuibo , anh @at-thinhnguyen 
 
![list_comment2](https://user-images.githubusercontent.com/29195110/28905678-64d7f2a6-783c-11e7-9618-f043fa6dcbbb.jpg)

**Comment by at-trungtranqn** [comment]
![list_cm2](https://user-images.githubusercontent.com/29195110/28906041-e0f65aba-783e-11e7-8a0f-6799184f7e17.jpg)
mình update rồi nha @at-nhuibo :)

**Comment by ghost** [comment]
Thanks @at-trungtranqn.
LGTM.

**Comment by at-trungtranqn** [comment]
thank you :)
