### ISSUE TITLE
Admin - Manager Comment - Delete Comment Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#56]

**Comment by at-trungtranqn** [comment]
![Delete_comment.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46cc9196269686968ce6b24ea153e4d665043761260ea62864c7b96aea1b2d05585e4bf9425a0944aef1892ba2b43d22db550eeec3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc0ed3927e68a8c4f3e1b1755.jpg)

**Comment by ghost** [comment]
Cần phải kiểm tra comment có tồi tại hay không nữa

**Comment by annq3012** [comment]
Dạ đây là phần quản lý comment bên admin, nên delete cmt thì ở trên list cmt rồi ạ

**Comment by ghost** [comment]
LGTM
