### ISSUE TITLE
Admin - Manager Comment - Update Comment Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#57]

**Comment by at-trungtranqn** [comment]
![Edit_comment.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46cd909337bd80a682e4ba4db01fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8238a4584b3bc8a49c4ea3d22e28e8f462c53.jpg)

**Comment by ghost** [comment]
Chức năng này không cần thiết :)

**Comment by ghost** [comment]
@at-minhnguyen Cái này giờ sao đây?
