### ISSUE TITLE
Admin - Manager Comment - Search Comment Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#58]

**Comment by at-trungtranqn** [comment]
![search_comment.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fb919b31818b968ce6b24ea153e4d665043761260ea62864c7b96aea1b2d05585e4bf9425a0944aef1892ba2b43d22db550eeec3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc0ed3927e7898e46371e1755.jpg)

**Comment by ghost** [comment]
Chưa có nơi Input
Mình có phần search nâng cao không nhỉ?

**Comment by annq3012** [comment]
Search là ở nơi Bảng IndexComment có thẻ input để nhập và tìm kiếm rồi anh. Tìm kiếm nâng cao là sao anh?

**Comment by ghost** [comment]
- Chắc ko cần search nâng câo
-  Nhầm alt Delete rùi
- Ghi cái input đó ra chứ  "Input values" thì không biết input vào đâu

**Comment by annq3012** [comment]
![cmt-search.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46eb998e6e9186a89deab701e81fe086264c22703d46f96925dcb52ce8132e045c5d18ac13505f44f8fb8879f7bf3973984019af80330b2b9b645bf9fa9015ad03bc2a8a4a85b7b9824fc5e03a2ce58b9d02.jpeg)
