### ISSUE TITLE
Admin - Manager News - Create News Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#59]

**Comment by at-trungtranqn** [comment]
![create_new.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46eb869f2296869681eca801e81fe086264c22703d46f96925dcb52ce8132e045c5d18ac13505f44f8fb8879f7bf3973984019af80330b2b9b645bf9fa9015ad03bc2a8a4a85b6b98e4ec0e83e20e0829d02.jpg)

**Comment by ghost** [comment]
Thiếu nhập thông tin :D

**Comment by annq3012** [comment]
![news-create.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46e6918d30cf80bb8ae8ab46e611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b826814e80b6bd8e4bc7ea382ce28e875d73.jpeg)

**Comment by ghost** [comment]
- Check validate riêng, với query database riêng

**Comment by annq3012** [comment]
![news-create.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46e6918d30cf80bb8ae8ab46e611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b826814e80b6bd8f44c3e13d22e689865d73.jpeg)

**Comment by at-trungtranqn** [comment]
@at-thinhnguyen  a  ơi check giúp em luôn nha
