### ISSUE TITLE
Admin - Manager News - Update News Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#60]

**Comment by at-trungtranqn** [comment]
![update_news.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fd849e2296869681eca850e611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b826814e80b6bc8f48c1e13821e28d8b5d73.jpg)

**Comment by ghost** [comment]
Đáng lẽ bước 5 là user input new data. Mà thôi. Chả sao cả.
LGTM. Thanks.
