### ISSUE TITLE
Admin - Manager News - Delete News Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#61]

**Comment by at-trungtranqn** [comment]
![delete_news.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46ec91962696869681eca850e611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b921814e80b6bc8f48c1e13a2de38b885d73.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
