### ISSUE TITLE
Admin - Manager News - Search News Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#62]

**Comment by at-trungtranqn** [comment]
![search_news.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fb919b31818b9681eca850e611b2843b492d762a10e17132d0ba7ebb152a540a5c4cfa410a5744fcfd8b2af4e73575894e17ff933c0120996048e6edc00db513b826814e80b6bc8f48c1e13e23ef898f5d73.jpg)

**Comment by at-nhuibo** [comment]
LGTM. Thanks.

**Comment by ghost** [comment]
Cái 4 và 5# á. Vì sao lại alt - Delete?

**Comment by ghost** [comment]
@at-trungtranqn Check this one please. Thanks.

**Comment by at-trungtranqn** [comment]
cái ni của Ân làm nha Nhứi, để mình nói Ân Fix  ..Mình up ảnh lên giúp ân thôi 
:) . Thank you

**Comment by annq3012** [comment]
![imgpsh_fullsize.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46e1999d33918b9689fcb34fb754ea916b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d87b0b68b49c0e93b21ee8a8e493c1a010ac4.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
