### ISSUE TITLE
Admin - Manager News - View List Of News Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#63]

**Comment by at-trungtranqn** [comment]
![list_news.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46e49d8937bd8dac98fafd0fe64de29b234324676b5ee17e29d3e77fee177e525d094efe49585f40fef8db7aafb33f62964e49bc8f3900299f7744eeaa880dbc00b0218e4f85b3b88b44c8ea3422e599c2.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
