### ISSUE TITLE
Admin - Manager News Category - Create Category Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#64]

**Comment by at-trungtranqn** [comment]
![create_category.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46eb869f229686968ce8ab46a352e28d6b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d87b0b68b49c0e83821e6838b493b16030ac4.jpg)

**Comment by ghost** [comment]
LGTM. Thanks.
