### ISSUE TITLE
Admin - Manager News Category - Update Category Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#65]

**Comment by at-trungtranqn** [comment]
![update_category.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fd849e229686968ce8ab46a352e28d6b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d86b7b68b49c0e83821e6838e4d3b1e020ac4.jpg)

**Comment by ghost** [comment]
@at-trungtranqn Trình tự các bước thì OK, tuy nhiên bị thiếu thôi. Bước 5 nên là input change data and click submit, sau đó mới check validate.

**Comment by annq3012** [comment]
![category-update.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46eb958e26858cbb96a4aa53a05ce4916b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d87b0b68b49c0e93923e0898e4b3918070ac4.jpeg)

**Comment by ghost** [comment]
LGTM. Thanks.
