### ISSUE TITLE
Admin - Manager News Category - Search Category Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#67]

**Comment by at-trungtranqn** [comment]
![search_category.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46fb919b31818b968ce8ab46a352e28d6b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d86b7b68b49c0e83821e68c8b4f381d000ac4.jpg)

**Comment by ghost** [comment]
Ảnh với tiêu đề ko giống nhau @@, tên function đặt tên cho dễ hiểu: deleteCategory()

**Comment by annq3012** [comment]
![category-search.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46eb958e26858cbb96a4ac46a54ff39c6b0a65633b0ba92e7391a172fd1722570b584fa9145b5d12fcab812ba6b23e71d80d02e8d27f4366846c4ff8e7df46f554f832815d87b0b68b49c0e93923ef88884e3d160c0ac4.jpeg)

**Comment by ghost** [comment]
- Chưa biết input value vào đâu
- Thiếu trường hợp có hoặc ko có dữ liệu

**Comment by annq3012** [comment]
![cat-search.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46eb958e6e9186a89deab701e81fe086264c22703d46f96925dcb52ce8132e045c5d18ac13505f44f8fb8879f7bf3973984019af80330b2b9b645bf9fa9015ad03bc2a8a4a85b7b88d4ac8e03d20e08d9d02.jpeg)

**Comment by ghost** [comment]
- Vì đang ở GUI category mà "Input value" thì không biết input vào đâu

**Comment by annq3012** [comment]
![cat-search.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46eb958e6e9186a89deab701e81fe086264c22703d46f96925dcb52ce8132e045c5d18ac13505f44f8fb8879f7bf3973984019af80330b2b9b645bf9fa9015ad02bb2a8a4a85b7b98248c2ef3927ee889d02.jpeg)

**Comment by at-trungtranqn** [comment]
@at-thinhnguyen review giúp a ơi :)

**Comment by ghost** [comment]
ok :D
