### ISSUE TITLE
Admin - Manager News Category - View List Of Category Sequence Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#68]
yuio

**Comment by at-annguyen** [comment]
abc

**Comment by at-trungtranqn** [comment]
![list_category.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46e49d8937bd80a89becb84cb644b2d86b56357c2301a03f32dfa17de6147f565e5a1baf430e5f16f4f9892fa4b76e21835908ffcd7f1d2598694ef1e1c84afd13b03289498fb7b98a4cc5ec3c22e78e8e4d360c48.jpg)

**Comment by ghost** [comment]
Tên của function nếu không dài lắm thì ghi đầy đủ ra cho dễ đọc: getCategoryList()

**Comment by annq3012** [comment]
![category-viewjpeg.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed7b6ca1a9d001a112f6d/125516c66e82c728ace21e0d46eb958e26858cbb96a4a94aa14afa842c41653f6b14b1247a80e03cfd18395456591aab405d0a47feaf8979aeb63c74885d59bcd8685c66da2f53fde6d640e258f075c95d8fa4be8c46c1ed3d24e38d874a3c17001e81ed10.jpg)
