### ISSUE TITLE
User - Login Sequence Diagram

### ISSUE THREAD

**Issue by duocnguyenc** [AT-PHPIntership/hotel-booking#69]
![login.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed67411f7b9001f9d94ff/125516c66e82c728ace21e0d46e49b9d2a8cc1e5cdf9ad4cae58f3806b1c65267052a77c21d0e67bed442b03575f4ea843590d15f5fc8a39baa47e21d40854b088270a36d43703aebe881eba01bb248c4d87b0ba8a4ac3fa70.jpg)

**Comment by ghost** [comment]
Thiếu nhập thông tin login
