### ISSUE TITLE
User - Delete Booking Room History  Sequence Diagram

### ISSUE THREAD

**Issue by duocnguyenc** [AT-PHPIntership/hotel-booking#71]
![deleteBookHis.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed67411f7b9001f9d94ff/125516c66e82c728ace21e0d46ec91962696868b80e6b46bad4eb2d86b56357c2301a03f32dfa17de6147f565e5a1baf430e5f16f4f9892fa4b76e21835908ffcd7f1d2598694ef1e1c84afd13b03289498fb7b98a4dc4ef3f26e5898d47360c48.jpg)

**Comment by ghost** [comment]
Mình nghĩ thiếu trường hợp cancel confirm
