### ISSUE TITLE
Design ERD diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#72]

**Comment by at-namnguyen** [comment]
[Uploading erd.png...]

**Comment by karify98** [comment]
![erd.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46ed869e61cec1b99de6b546a749b2ce6b137e252d53f27e75d6b12eef4023515f5b4cad13095641ffeb9539e4e76224d50152a7842f4d7ed43f17a6b9871fbf09bc23834e86b6b8835e8d.png)

**Comment by ghost** [comment]
@at-namnguyen @at-trungtranqn 
- 1 hotel có nhiều service, 1 service có thể thuộc nhiều hotel => xem lại chỗ hotel vs service nha
- chỗ reservation => nếu muốn đặt các phòng khác nhau với số lượng nhiều hơn 1 thì lưu thế nào
- Chỗ places -> nên có parent_id nữa, default là null, để thêm các thành phố trực thuộc tỉnh hoặc huyện, quận tiêu biểu.

Mọi ng check giúp vs nha!

**Comment by HT-yen** [comment]
![ERD.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edac7ca1a9d001a112f79/125516c66e82c728ace21e0d46cda6be61cec1b99de6b546a749b2ce6b137e252d53f27e75d6b12eef4023515f5b4cad13095641ffeb9539e4e76224d50152a7842f4d7ed43f17a6b9871fbe03b8268b4687bebf8e5e8d.png)

tụi  em fix lại ERD rồi, check lại giúp tụi em với.

**Comment by ghost** [comment]
@at-yenho @at-trungtranqn còn có 1 cái nữa là OK.
> Chỗ places -> nên có parent_id nữa, default là null, để thêm các thành phố trực thuộc tỉnh hoặc huyện, quận tiêu biểu.

**Comment by ghost** [comment]
LGTM. Thanks all.

**Comment by ghost** [comment]
@at-thinhnguyen @at-minhnguyen Please check it and reply if it's OK. Thanks.

**Comment by ghost** [comment]
- introduce của hotels nên để kiểu TEXT, vì VARCHAR có 255 ký tự sợ không đủ (content của News, Static_page nữa)
- Nên lưu ý thêm field created_at or updated_at cho những bảng cần thiết, vd: hotel_services, feedback thì ko cần updated_at
- Image chưa địa chỉ image nên không nên đặt tên field là "content"

**Comment by at-thinhnguyen** [comment]
Bổ sung:
- Bảng reservations target với target_id mục đích nào gì nhỉ, mình nghĩ chỉ cần hotel_id
Đợi A Nhứi confirm

**Comment by ghost** [comment]
@at-nhuibo nhui

Cái bảng `guest` dùng làm gì vậy?

**Comment by ghost** [comment]
@at-vienle Để lưu thông tin của khách vãng lai (không đăng kỹ thành viên) họ muốn đặt phòng.

**Comment by at-trungtranqn** [comment]
e mới update lại ERD chỗ place thêm image
![ERD-1-8-2017.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ed852ca1a9d001a112f73/125516c66e82c728ace21e0d46cda6be6ed3cef1c2bbef12f31fbcd6395428792c07b7692ac7b671e9462c505a0a4dae17580d4cfcf98d29a7e46d798f5f19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc8b49c6ef3b24e18d8a4f2c53.png)

**Comment by ghost** [comment]
@at-nhuibo @at-thinhnguyen Check lại anh với

**Comment by ghost** [comment]
@at-trungtranqn @at-yenho 
- Static page ko có soft delete nha! Nó cũng ko có chức năng delete. Chi được phép sửa thôi.
- target_id của bảng images và reservation là integer 10 thôi nhá!

**Comment by at-trungtranqn** [comment]
![erd update](https://user-images.githubusercontent.com/29195110/28821908-7c30d438-76e1-11e7-8efc-a866e70af6a9.png)
@at-nhuibo review lại giúp mình nha

**Comment by ghost** [comment]
LGTM. Thanks.
