### ISSUE TITLE
Design Class Diagram

### ISSUE THREAD

**Issue by at-trungtranqn** [AT-PHPIntership/hotel-booking#75]

**Comment by karify98** [comment]
![class.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596edc4211f7b9001f9d950b/125516c66e82c728ace21e0d46eb989b3091c1e5cdf9ad4cae58f3806b1c65267052a77c21d0e67bed442b03575f4ea843590d15f5fc8a39baa47e21d40854b088270a36d43703afb9881eba01bb24824981bebe8d48c9fa70.jpg)

**Comment by ghost** [comment]
Update giúp anh các điểm sau:
- create_at => createdAt
- update_at => updatedAt
- is_admin => isAdmin
- is_active => isActive
...
Nói chung tên thuộc tính update sang camelCase hết nhé mọi người

**Comment by karify98** [comment]
Em mới update a check lại giúp em

**Comment by ghost** [comment]
Class cần update thêm, thuộc tính sai chính tả:
- Image
- Guest
- User
- Feedback
- Hotel
- Service
- Place
- News

**Comment by karify98** [comment]
a rv giúp e sớm cho xong phần này luôn
